#!/bin/sh /etc/rc.common
USE_PROCD=1
START=98
start_service() {
    local iface dns
    iface=$(ubus call network.interface.wwan status | jsonfilter -e '@.l3_device')
    dns=$(ubus call network.interface.wwan status | jsonfilter -e '@.route[@.target="0.0.0.0"].nexthop' | head -n 1)
    [ -n "$iface" ] && [ -n "$dns" ] || return 1
    procd_open_instance
    procd_set_param command /usr/local/bin/router-joiner --config /etc/mobile-backup/vk/config.json --dns "$dns:53" --interface "$iface" --authorize-vk
    procd_set_param env GOMAXPROCS=2
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
